### PR TITLE
change default value to match docstring in ivb

### LINKED ISSUE #118: mismatch between docstring and default values
in https://github.com/svalinn/parastell/blob/002adc28f47952ad31ed29c19843084d37aae884/parastell/invessel_build.py#L101
a default value of 67 is assigned to `self.num_rib_pts`, the docstring says it should be 61.

### PR DESCRIPTION
**Pull request by Edgar-21**
fixes #118 

@connoramoreno I just guessed that this should be updated to match the docstring rather than the other way around, lmk if that is not the case

### CODE REVIEW

**Comment by connoramoreno** [comment]
Let's keep the default value at 67 and just update the docstring. Good catch!

**Comment by Edgar-21** [comment]
black autoformatting got to one of these files hence the big diff

**Comment by Edgar-21** [comment]
CI seems to be failing on `test_magnet_coils.py` for some reason? I didn't touch anything to do with that in this pr

**Comment by Edgar-21** [comment]
nevermind its because this is on my fork, I'll have to reopen a different pr doing the same thing

**Pull request closed without merging**
