### PR TITLE
add normal test for CI

### PR DESCRIPTION
**Pull request by gonuke**

### CODE REVIEW

**Comment by gonuke** [comment]
This should be the last thing before transitioning to the OO version

**Comment by connoramoreno** [comment]
I'm still trying to wrap my mind around using GitHub Actions for CI. What's the purpose of having tests triggered by both pull requests and commit pushes? And something I'm still slightly unclear about is which version of the code is being tested for each GitHub Action workflow.

**Comment by gonuke** [comment]
The other test only runs when a push happens and one of those two specific files changes: the GH action itself or the Dockerfile.

This test only runs on a pull request when any file changes.  We could, technically, NOT run this test when those two files change.

**Review by connoramoreno — APPROVED** [review]
Looks good to me! Thanks @gonuke

**Pull request merged**
